from pilha import Pilha


pilha = Pilha(5)
print(pilha.ver_topo())
print(pilha.getValores())
pilha.empilhar(1)
pilha.empilhar(2)
pilha.empilhar(3)
pilha.empilhar(4)
pilha.empilhar(5)
print(pilha.ver_topo())
print(pilha.getValores())
pilha.empilhar(6)
pilha.desempilhar()
print(pilha.ver_topo())
print(pilha.getValores())
pilha.desempilhar()
pilha.desempilhar()
pilha.desempilhar()
print(pilha.ver_topo())
print(pilha.getValores())
pilha.empilhar(6)
print(pilha.ver_topo())
print(pilha.getValores())